ssmspath=C:\Program Files\Microsoft SQL Server Management Studio 22\Release\Common7\IDE

#trustServerCertificate=true

# Configure encryption settings for SSMS connection: optional|mandatory|strict
#encrypt=optional

#loginActions=s::#i0118::{password}||c::#idSIButton9::10||o::#idTxtBx_SAOTCC_OTC::{Target.TotpCodes}::3||c::#idSubmit_SAOTCC_Continue::10||c::#idBtn_Back::5

#browserInputDelay=1000

#seconds to wait for UI elements to appear before giving up, applied to the v, o, s action types. Action type c (click) has its own timeout that can be set in the loginActions string.
#uiaWaitTimeout=60

#dumpStdinToLog=false